parserOptions:
  ecmaVersion: 2015
  sourceType: 'module'

env:
  es6: true
  browser: true
  commonjs: true
  mocha: true

extends: 'htmlacademy/es6'

rules:
  indent: ["error", "tab", {"SwitchCase": 1}]
  no-tabs: ["off"]
